// client/src/pages/Information.jsx
import React from 'react';

const Information = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold mb-6 text-center">Information</h1>
      <div className="max-w-3xl mx-auto space-y-4 text-slate-700">
        <p>
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
        </p>
        <p>
          The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop under 2 tons by 2050.
        </p>
      </div>
    </div>
  );
};

export default Information;
